name: Knockback
description: A customizable knockback plugin for PocketMine-MP servers
author: Diduhless
website: https://twitter.com/Diduhless
main: Knockback\Knockback
version: "1.0.0"
api: 3.0.0


